const waifus = [
    "Yuuki Konno",
    "Silica",
    "Peppa Pig",
    "Isabella",
    "Near",
    "Yoshiko Tsushima",
    "The Goose",
    "Fischl",
    "Tier Harribel",
    "Naruko Anjou",
    "Firefoxchan",
    "Shana",
    "Ada Wong",
    "Meltryllis",
    "Jinx",
    "Captain Marvel (Carol Danvers)",
    "Charizard (SSB)",
    "Alexis Rhodes",
    "Muriel Bagge",
    "Karui",
    "SpiderGirl (Mayday Parker)",
    "Lisa Yadōmaru",
    "U-47",
    "Hana Inuzuka",
    "Seimei (SK)",
    "Maya Kuroki",
    "Azaka Kokutou",
    "Elena (KK)",
    "Illaoi",

]
module.exports = waifus;